name: MixerTTS_kss
transcript: data/kss/train_transcript.txt
val_transcript: data/kss/val_transcript.txt

sample_rate: 24000
n_fft: 1024
hop_size: 240
win_size: 1024
fmin: 0
fmax: 12000

phonemes: _ ᄀᄁᄂᄃᄄᄅᄆᄇᄈᄉᄊᄌᄍᄎᄏᄐᄑ하ᅣᅥᅦᅧᅨᅩᅪᅬᅭᅮᅯᅱᅲᅳᅴᅵᆨᆫᆮᆯᆷᆸᆼ
num_embeddings: 44
embedding_dim: 384
encoder_kernels: [11, 13, 15, 17, 19, 21]
decoder_kernels: [15, 17, 19, 21, 23, 25, 27, 29, 31]

pitch_loss_scale: 0.1
durs_loss_scale: 0.1
mel_loss_scale: 1.0
bin_loss_start_epoch: 100

batch_size: 8
max_epoch: 1000
save_and_val_every_n_epoch: 20

lr: 1e-1
betas: [0.9, 0.98]
weight_decay: 1e-6
fp_16: true
num_workers: 4